// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateUrl(ctx context.Context, arg CreateUrlParams) (Shurl, error)
	GetUrl(ctx context.Context, id int64) (Shurl, error)
	GetUrlFromHash(ctx context.Context, hash string) (Shurl, error)
	UpdateUrl(ctx context.Context, arg UpdateUrlParams) error
}

var _ Querier = (*Queries)(nil)
